---
# tasks file for roles/centos_configure

  - name: httpd installation
    yum:
      name: httpd
      state: latest
      update_cache: yes

  - name: Starting httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Stop Firewall
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Installing PCU
    yum:
      name: policycoreutils-python-utils
      state: latest
      update_cache: yes

  - name: Creating Virtual Host Directory
    file:
      path: /var/www/matienzo_domain_centos
      state: directory
      owner: "{{ owner }}"
      group: "{{ owner }}"
      mode: '0755'

  - name: Creating log directory
    file:
      path: /var/www/matienzo_domain_centos/log
      state: directory
      owner: "{{ owner }}"
      group: "{{ owner }}"
      mode: '0755'

  - name: Creating html directory
    file:
      path: /var/www/matienzo_domain_centos/html
      state: directory
      owner: "{{ owner }}"
      group: "{{ owner }}"
      mode: '0755'

  - name: Copying index.html from files folder
    copy:
      src: index.html
      dest: /var/www/matienzo_domain_centos/html/index.html
      owner: "{{ owner }}"
      group: "{{ owner }}"
      mode: '0755'

  - name: Creating sites-available
    file:
      path: /etc/httpd/sites-available
      state: directory
      mode: '0755'

  - name: Creating sites-enabled
    file:
      path: /etc/httpd/sites-enabled
      state: directory
      mode: '0755'

  - name: Creating httpd.conf
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: "IncludeOptional sites-enabled/*.conf"

  - name: Copying of conf file to sites-available
    copy:
      src: matienzo_domain_centos.conf
      dest: /etc/httpd/sites-available/matienzo_domain_centos.conf
      owner: "{{ owner }}"
      group: "{{ owner }}"
      mode: '0755'

  - name: Linking sites directory
    file:
      src: /etc/httpd/sites-available/matienzo_domain_centos.conf
      dest: /etc/httpd/sites-enabled/matienzo_domain_centos.conf
      state: link

  - name: Setsebool
    seboolean:
      name: httpd_unified
      state: yes
      persistent: yes

  - name: Restarting httpd
    service:
      name: httpd
      state: restarted
